### PR TITLE
Update kafka-monitor-start.bat to use the correct class path

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by lindong28** [comment]
@smccauliff Can you review this? Thanks.

**Comment by smccauliff** [comment]
run-class.bat emits some kind of error message that references the old class name

**Comment by smccauliff** [comment]
Did you actually test this on windows?

**Comment by lindong28** [comment]
@smccauliff You are right. More change is needed in kmf-run-class.bat. I have updated the patch to fix it. I haven't tested it on Windows since I don't have window machine. I think it is probably better than not fixing it. We can ask that user to test it after the fix. What do you think?

**Pull request merged**
