### PR TITLE
Add topic creation to ConsumeService and minor text formatting

### PR DESCRIPTION
**Pull request by WarrenGreen**
- Allow for topic creation to work when using separate produce/consume clusters by adding topic creation in the ConsumeService
- Fix minor text formatting in ProduceService

### CODE REVIEW

**Comment by lindong28** [comment]
Can you explain why should ConsumeService create topic? In general the application who produce data will create topic.

**Comment by WarrenGreen** [comment]
When monitoring a mirror maker across two clusters, it will currently only create a topic on the producer cluster and will not on the consumer cluster. With this change, it will create the topic as needed on both clusters. If there is only one cluster that both the producer/consumer use then one of them will successfully create the topic and the other will return the # of partitions that were created for the topic.

**Comment by smccauliff** [comment]
I'm confused about this can you show me on the white board?

**Comment by lindong28** [comment]
But adding this in ConsumeService wouldn't solve the problem where we monitor a pipline of three cluster. The topic in the middle middle also needs to have proper number of partitions and these partitions need to be distributed across broker properly, which is the functionality of the TopicManagementService. Instead of asking ConsumeService to create topic, maybe we should simply instantiate one TopicManagementService per cluster.

**Pull request closed without merging**
