### PR TITLE
Remove dash from schema

### PR DESCRIPTION
**Pull request by lindong28**

### CODE REVIEW

**Comment by lindong28** [comment]
Remove dash from scheme name so that it can be parsed by avro 1.7.

**Comment by smccauliff** [comment]
I can't think of any problems this would cause unless someone had an existing consumer that was far behind in consuming messages, but that's actually a real problem if that is happening.  Did you test this?  When you merge squash and merge can you change the description so it says avro 1.7 rather than 1.4.

**Comment by lindong28** [comment]
This should not cause issue because consumer used by Kafka Monitor will always consume from latest offset. I have tested it and it works. Why should we change the description to say avro 1.7? It seems that avro 1.4 already has this requirement. It is just not enforced until avro 1.7.

**Comment by smccauliff** [comment]
But we are making this change for 1.7 compatibility.    Someone reading this may want to know that.

**Comment by lindong28** [comment]
@smccauliff Personally I don't think it matters. Because we should make this change anyway since it is specified by avro 1.4 and later. But it doesn't really matters. I have changed the description to 1.7.

**Comment by smccauliff** [comment]
Remove dash from scheme name so that it meets the naming conversion of avro library.

The schema name should meet the following requirement according to avro 1.7 specification (https://avro.apache.org/docs/1.7.7/spec.html#Names)

start with [A-Za-z_]
subsequently contain only [A-Za-z0-9_]

**Comment by smccauliff** [comment]
Thanks for dealing with the avro upgrade complexities.

**Comment by lindong28** [comment]
@smccauliff Thanks for the review.

**Pull request merged**
