### PR TITLE
Add travis configuration

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by lindong28** [comment]
Can you explain the benefits of this patch?

**Comment by gliptak** [comment]
Each pull requests will be built (rebased on ```master```),  ensuring that the build is not broken.

You can review an example build at https://github.com/linkedin/pinot/pull/888

**Comment by lindong28** [comment]
@gliptak Cool. Thank you!

**Comment by gliptak** [comment]
Might have to enable the repo at https://travis-ci.org/linkedin/kafka-monitor (you can access the repos in the top right corner)

**Comment by lindong28** [comment]
@gliptak Sure. I just enabled it.

**Comment by lindong28** [comment]
I see the following comment: "This is not an active repository. You don't have sufficient rights to enable this repo on Travis. Please contact the admin to enable it or to receive admin rights yourself."

I may need to email admin of LinkedIn github repositories about this.

**Comment by gliptak** [comment]
Something is still not right. There should have been a checkmark on:

https://github.com/linkedin/kafka-monitor/pull/38

and ```master``` should have been built with the latest commit ...

**Comment by gliptak** [comment]
I just refreshed your comment above. I'm not sure what privileges you have as a ```member```

**Comment by gliptak** [comment]
@lindong28 Goto page https://github.com/orgs/linkedin/people and contact```owner```s. Those people should be able to enable the repo at travis-ci

**Comment by lindong28** [comment]
@dnozay Can you help us enable auto-build verification of this repository at https://travis-ci.org/linkedin/kafka-monitor? I don't seem to have the permission to enable this. If no, who else should I contact to resolve this problem? Thanks!

**Pull request merged**
